# Services
services:

  # Newsletter Service
  newsletter-app:
    container_name: newsletter-app
    #image: wordpress:php8.1-fpm
    image: bitnami/wordpress-nginx
    environment:
      WORDPRESS_USERNAME: ${WORDPRESS_USERNAME}
      WORDPRESS_PASSWORD: ${WORDPRESS_PASSWORD}
      WORDPRESS_EMAIL: ${WORDPRESS_EMAIL}
      WORDPRESS_FIRST_NAME: ${WORDPRESS_FIRST_NAME}
      WORDPRESS_LAST_NAME: ${WORDPRESS_LAST_NAME}
      WORDPRESS_BLOG_NAME: ${WORDPRESS_BLOG_NAME}
      WORDPRESS_PLUGINS: ${WORDPRESS_PLUGINS}
      WORDPRESS_AUTO_UPDATE_LEVEL: ${WORDPRESS_AUTO_UPDATE_LEVEL}
      WORDPRESS_DATABASE_HOST: ${WORDPRESS_DATABASE_HOST}
      WORDPRESS_DATABASE_PORT_NUMBER: ${WORDPRESS_DATABASE_PORT_NUMBER}
      WORDPRESS_DATABASE_USER: ${WORDPRESS_DATABASE_USER}
      WORDPRESS_DATABASE_PASSWORD: ${WORDPRESS_DATABASE_PASSWORD}
      WORDPRESS_DATABASE_NAME: ${WORDPRESS_DATABASE_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_SKIP_BOOTSTRAP: ${WORDPRESS_SKIP_BOOTSTRAP}
      WORDPRESS_AUTH_KEY: ${WORDPRESS_AUTH_KEY}
      WORDPRESS_SECURE_AUTH_KEY: ${WORDPRESS_SECURE_AUTH_KEY}
      WORDPRESS_LOGGED_IN_KEY: ${WORDPRESS_LOGGED_IN_KEY}
      WORDPRESS_NONCE_KEY: ${WORDPRESS_NONCE_KEY}
      WORDPRESS_AUTH_SALT: ${WORDPRESS_AUTH_SALT}
      WORDPRESS_SECURE_AUTH_SALT: ${WORDPRESS_SECURE_AUTH_SALT}
      WORDPRESS_LOGGED_IN_SALT: ${WORDPRESS_LOGGED_IN_SALT}
      WORDPRESS_NONCE_SALT: ${WORDPRESS_NONCE_SALT}
      PHP_ENABLE_OPCACHE: ${PHP_ENABLE_OPCACHE}
      PHP_EXPOSE_PHP: ${PHP_EXPOSE_PHP}
      PHP_MAX_EXECUTION_TIME: ${PHP_MAX_EXECUTION_TIME}
      PHP_MAX_INPUT_TIME: ${PHP_MAX_INPUT_TIME}
      PHP_MAX_INPUT_VARS: ${PHP_MAX_INPUT_VARS}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
      PHP_POST_MAX_SIZE: ${PHP_POST_MAX_SIZE}
      PHP_UPLOAD_MAX_FILESIZE: ${PHP_UPLOAD_MAX_FILESIZE}
    ports:
      - 1003:8080
    networks:
      - newsletter
      - mariadb
    volumes:
      #- ./.docker/nginx/newsletter.conf:/etc/nginx/sites-available/default.conf
      - ~/dev/data/docker/dclm_newsletter:/bitnami/wordpress
    restart: always

networks:
  newsletter:
    name: newsletter
  mariadb:
    name: mariadb

# volumes:
#   newsletter_data: {}