# Services
services:

  # Newsletter Service
  newsletter-app:
    container_name: newsletter-app
    #image: bitnami/wordpress-nginx
    image: opeoniye/wordpress-nginx
    user: ubuntu
    environment:
      WORDPRESS_USERNAME: ${WORDPRESS_USERNAME}
      WORDPRESS_PASSWORD: ${WORDPRESS_PASSWORD}
      WORDPRESS_EMAIL: ${WORDPRESS_EMAIL}
      WORDPRESS_FIRST_NAME: ${WORDPRESS_FIRST_NAME}
      WORDPRESS_LAST_NAME: ${WORDPRESS_LAST_NAME}
      WORDPRESS_BLOG_NAME: ${WORDPRESS_BLOG_NAME}
      WORDPRESS_PLUGINS: ${WORDPRESS_PLUGINS}
      WORDPRESS_ENABLE_HTTPS: ${WORDPRESS_ENABLE_HTTPS}
      WORDPRESS_SKIP_BOOTSTRAP: ${WORDPRESS_SKIP_BOOTSTRAP}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      #
      WORDPRESS_DATABASE_HOST: ${WORDPRESS_DATABASE_HOST}
      WORDPRESS_DATABASE_PORT_NUMBER: ${WORDPRESS_DATABASE_PORT_NUMBER}
      WORDPRESS_DATABASE_USER: ${WORDPRESS_DATABASE_USER}
      WORDPRESS_DATABASE_PASSWORD: ${WORDPRESS_DATABASE_PASSWORD}
      WORDPRESS_DATABASE_NAME: ${WORDPRESS_DATABASE_NAME}
      WORDPRESS_DB_COLLATE: ${WORDPRESS_DB_COLLATE}
      WORDPRESS_ENABLE_DATABASE_SSL: ${WORDPRESS_ENABLE_DATABASE_SSL}
      WORDPRESS_VERIFY_DATABASE_SSL: ${WORDPRESS_VERIFY_DATABASE_SSL}
      WORDPRESS_DATABASE_SSL_CA_FILE: ${WORDPRESS_DATABASE_SSL_CA_FILE}
      #
      # MYSQL_CLIENT_FLAVOR: ${MYSQL_CLIENT_FLAVOR}
      # MYSQL_CLIENT_DATABASE_HOST: ${MYSQL_CLIENT_DATABASE_HOST}
      # MYSQL_CLIENT_DATABASE_PORT_NUMBER: ${MYSQL_CLIENT_DATABASE_PORT_NUMBER}
      # MYSQL_CLIENT_DATABASE_ROOT_USER: ${MYSQL_CLIENT_DATABASE_ROOT_USER}
      # MYSQL_CLIENT_DATABASE_ROOT_PASSWORD: ${MYSQL_CLIENT_DATABASE_ROOT_PASSWORD}
      # MYSQL_CLIENT_CREATE_DATABASE_NAME: ${MYSQL_CLIENT_CREATE_DATABASE_NAME}
      # MYSQL_CLIENT_CREATE_DATABASE_USER: ${MYSQL_CLIENT_CREATE_DATABASE_USER}
      # MYSQL_CLIENT_CREATE_DATABASE_PASSWORD: ${MYSQL_CLIENT_CREATE_DATABASE_PASSWORD}
      # MYSQL_CLIENT_CREATE_DATABASE_CHARACTER_SET: ${MYSQL_CLIENT_CREATE_DATABASE_CHARACTER_SET}
      # MYSQL_CLIENT_CREATE_DATABASE_COLLATE: ${MYSQL_CLIENT_CREATE_DATABASE_COLLATE}
      # MYSQL_CLIENT_ENABLE_SSL: ${MYSQL_CLIENT_ENABLE_SSL}
      # MYSQL_CLIENT_SSL_CA_FILE: ${MYSQL_CLIENT_SSL_CA_FILE}
      #
      WORDPRESS_SMTP_HOST: ${WORDPRESS_SMTP_HOST}
      WORDPRESS_SMTP_PORT: ${WORDPRESS_SMTP_PORT}
      WORDPRESS_SMTP_USER: ${WORDPRESS_SMTP_USER}
      WORDPRESS_SMTP_PASSWORD: ${WORDPRESS_SMTP_PASSWORD}
      #
      PHP_ENABLE_OPCACHE: ${PHP_ENABLE_OPCACHE}
      PHP_EXPOSE_PHP: ${PHP_EXPOSE_PHP}
      PHP_MAX_EXECUTION_TIME: ${PHP_MAX_EXECUTION_TIME}
      PHP_MAX_INPUT_TIME: ${PHP_MAX_INPUT_TIME}
      PHP_MAX_INPUT_VARS: ${PHP_MAX_INPUT_VARS}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
      PHP_POST_MAX_SIZE: ${PHP_POST_MAX_SIZE}
      PHP_UPLOAD_MAX_FILESIZE: ${PHP_UPLOAD_MAX_FILESIZE}
      #
      WORDPRESS_AUTH_KEY: ${WORDPRESS_AUTH_KEY}
      WORDPRESS_SECURE_AUTH_KEY: ${WORDPRESS_SECURE_AUTH_KEY}
      WORDPRESS_LOGGED_IN_KEY: ${WORDPRESS_LOGGED_IN_KEY}
      WORDPRESS_NONCE_KEY: ${WORDPRESS_NONCE_KEY}
      WORDPRESS_AUTH_SALT: ${WORDPRESS_AUTH_SALT}
      WORDPRESS_SECURE_AUTH_SALT: ${WORDPRESS_SECURE_AUTH_SALT}
      WORDPRESS_LOGGED_IN_SALT: ${WORDPRESS_LOGGED_IN_SALT}
      WORDPRESS_NONCE_SALT: ${WORDPRESS_NONCE_SALT}
    ports:
      - 1003:8080
    networks:
      - newsletter
    volumes:
      #- ./.docker/nginx/newsletter.conf:/etc/nginx/sites-available/default.conf
      - ./data-prod:/bitnami/wordpress
      - /var/docker/ssl/rds:/opt/bitnami/ssl
    restart: always

networks:
  newsletter:
    name: newsletter